# Spanish

["gui"]
disconnect = "Desconectar"
dismiss = "Descartar"
dismiss_far = "Descartar"
kicked = "Expulsado"
inventory = "Inventario..."
cancel = "Cancelar"

["gui.options"]
enablereverb = "Activar reverberaci칩n"
mastervolume = "Volumen de sonido (%d%%)"
resourcepacks = "Paquetes de recursos"

["gui.title"]
startgame = "Iniciar partida"
options = "Opciones"
quit = "Salir"
ip = "IP"
port = "Puerto"
username = "Nombre de usuario"

["kick"]
generic = "No se ha especificado una raz칩n"
existingusername = "Nombre de usuario ya existente"
wrongprotocol = "Protocolo incorrecto"
invalidusername = "Nombre de usuario inv치lido"
banned = "Usuario baneado"
closing = "El servidor est치 cerrando"


["msg"]
joined = "%s se ha unido a la partida."
left = "%s ha abandonado la partida."
opped = "%s ha sido promovido a operador."
deopped = "%s ha sido depromovido."
youhaveop = "Tienes privilegios de operador en este servidor."